version: "3.9"

services:
  postgres:
    image: postgres:16.9
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - .env

  
  analytics:
    build: ./analytics
    depends_on:
      - postgres
    ports:
      - "8001:8001"
    env_file:
      - .env

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev -- --host 0.0.0.0

volumes:
  db-data: